/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dyadav' at '5/7/18 7:45 PM' with Gradle 2.14.1
 *
 * @author dyadav, @date 5/7/18 7:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
